language: generic
sudo: required
branches:
  except:
    - /^v[0-9]*/
before_script:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -y
- sudo apt-get install armake -y
script:
- export VERSION=`cat description.ext  | grep -o 'onLoadName = ".*"' | grep -o 'v[0-9.][0-9.]*'`
- armake build -w unquoted-string -w redefinition-wo-undef -w excessive-concatenation -x ".*" -x "*.pbo" -x "*.md" . 7Cav_FullSpectrum_$VERSION.Malden.pbo
- git tag $VERSION
