language: generic
sudo: required
branches:
  except:
    - /^v[0-9]*/
before_script:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -y
- sudo apt-get install armake -y
script:
- export VERSION=`cat description.ext  | grep -o 'onLoadName = ".*"' | grep -o 'v[0-9.][0-9.]*'`
- armake build -w unquoted-string -w redefinition-wo-undef -w excessive-concatenation -x ".*" -x "*.pbo" -x "*.md" . 7Cav_FullSpectrum_$VERSION.Malden.pbo
- git tag $VERSION
deploy:
  if:
    branch: master
  provider: releases
  skip_cleanup: true
  file: '7Cav_FullSpectrum_$VERSION.Malden.pbo'
  on:
    branch: master
    repo: BojanOnTheInternet/7Cav_FullSpectrum_V4.Malden
  name: '7th Cavalry Full Spectrum $VERSION - Malden'
  api_key:
    secure: D/xKp+bM3OI6eZ3/ctx4aWnJyZyXG75JcqaP0fkjwSYdC1RPyBOu1El/KSLIZE4mgvvl3rRq+0PUR32MqejL0vdt/Sp8QfsVPHC/Hs8rIWn/ajIhY6nds9p2SgXyNBo2OLtHSvagYDV6/91Ou/0QvGS2nFwq5cQGYP9okRaMFMOKd1x6MMsquBgYFKiLX5o7Kt8T4DRmaQ+E1kN2hfWIhsyerrn8zQH63L7GHva/xRddWAjF6Zbxf8hg9VarEuEyz2K57HRlazpHRnz+4MsmN534DYAKfHFjr5ZbA5W7GaPY6mVgCnAyhYInaJxWKUVmkIYDDOwCoAnXfBzNyMuBXJuyKn+hC8+B+/UKaY2NCEkmXDJAgGQRoLfvJbtVfAWflZTd2M7+y0ksKScrdmRJEjM46g/ZLzWDnAuFZlvlinRHFK/SfF+/UEhuVie6MqhhJzl9nRE1jrX7PDTdMUPKgY9n/9u7nUeQUHzRhc7zdfvTfUOVZWqMdo/gFwETvDnIZaeLNmAztGRXAsUuy4nrlz0DjIIj4r7XvKyA6oTR9rlo1VCsxFefoEkVOWzCkd9v9fQHJ7dQYnyWxqcRLDsA54H2bNMFk/VeY+53iFqmIqunh23Z1ZaJQXvf7BuVPhQYsq9/ZEqkJgc4JABuRr7+/FA8qAJfu1rYrNo532cGhPM=
    file: ''
