class SPM
{
	tag = "SPM";
	class functions
	{
		file = "SPM";
		class spawnManagerPreInit { preInit = 1; };
		class strongpointPreInit { preInit = 1; };
		class missionPreInit { preInit = 1; };
		class categoryGuardObjectPreInit { preInit = 1; };
		class categoryForcePreInit { preInit = 1; };
		class categoryAirDefensePreInit { preInit = 1; };
		class categoryAirPatrolPreInit { preInit = 1; };
		class categoryAmmoCachesPreInit { preInit = 1; };
		class categoryAmmoDumpPreInit { preInit = 1; };
		class categoryRadioTowerPreInit { preInit = 1; };
		class categoryTransportPreInit { preInit = 1; };
		class transportRequestGroundPreInit { preInit = 1; };
		class transportRequestAirPreInit { preInit = 1; };
		class categoryHeadquartersPreInit { preInit = 1; };
		class categoryInfantryGarrisonPreInit { preInit = 1; };
		class categoryInfantryPatrolPreInit { preInit = 1; };
		class categoryCheckpointsPreInit { preInit = 1; };
		class categoryCommunicationCenterPreInit { preInit = 1; };
		class categorySatelliteCommunicationCenterPreInit { preInit = 1; };
		class categoryRadioCommunicationCenterPreInit { preInit = 1; };
		class categoryArmorIdlePreInit { preInit = 1; };
		class categoryArmorPreInit { preInit = 1; };
		class categoryCivilianVehiclesPreInit { preInit = 1; };
		class categoryDamagePulsePreInit { preInit = 1; };
		class categoryFleeWhenSignalledPreInit { preInit = 1; };
		class categoryMortarPreInit { preInit = 1; };
		class categoryMinesPreInit { preInit = 1; };
		class categoryParkedVehiclesPreInit { preInit = 1; };
		class categoryProvideGarrisonUnitPreInit { preInit = 1; };
		class categoryHeadquartersBivouackedPreInit { preInit = 1; };
		class categoryHeadquartersCounterattackPreInit { preInit = 1; };
		class categoryHeadquartersGarrisonPreInit { preInit = 1; };
		class categoryHeadquartersReinforcedPreInit { preInit = 1; };
		class chainPreInit { preInit = 1; };
		class clientInit {};
		class groupFromClasses {};
		class groupFromConfig {};
		class groupFromVehicleCrew {};
		class specialOperationsCommandPreInit { preInit = 1; };
		class missionAdvancePreInit { preInit = 1; };
		class missionDisruptMeetingPreInit { preInit = 1; };
		class missionInterceptConvoyPreInit { preInit = 1; };
		class missionMessagesPreInit { preInit = 1; };
		class missionRaidTownPreInit { preInit = 1; };
		class missionRescueHostagesPreInit { preInit = 1; };
		class objectiveCaptureConvoyVehiclePreInit { preInit = 1; };
		class objectiveCaptureManPreInit { preInit = 1; };
		class objectiveCompoundPreInit { preInit = 1; };
		class objectiveDebriefManPreInit { preInit = 1; };
		class objectiveDeliverManPreInit { preInit = 1; };
		class objectiveRescueManPreInit { preInit = 1; };
		class objectiveInteractObjectPreInit { preInit = 1; };
		class objectiveInteractObjectConvoyVehiclePreInit { preInit = 1; };
		class objectiveInteractObjectSimplePreInit { preInit = 1; };
		class objectiveInterceptVehiclePreInit { preInit = 1; };
		class objectiveDestroyObjectPreInit { preInit = 1; };
		class objectiveDestroyAmmoDumpPreInit { preInit = 1; };
		class objectiveDestroyCommunicationCenterPreInit { preInit = 1; };
		class objectiveDestroyRadioTowerPreInit { preInit = 1; };
		class objectiveDestroyVehiclePreInit { preInit = 1; };
		class objectiveMarkAmmoCachesPreInit { preInit = 1; };
		class objectiveMarkAmmoDumpPreInit { preInit = 1; };
		class objectiveMarkRadioTowerPreInit { preInit = 1; };
		class objectiveProtectCiviliansPreInit { preInit = 1; };
		class occupyEnterBuilding {};
		class occupyPreInit { preInit = 1;  };
		class patrolBuildings {};
		class patrolIntersections {};
		class patrolPerimeter {};
		class patrolPreInit { preInit = 1; };
		class patrolRoads {};
		class roadFollow {};
		class spawnGroup {};
		class spawnMineField {};
		class spawnPreInit { preInit = 1; };
		class spawnVehicle {};
		class strongpointGetChain {};
		class strongpointNavigationPreInit { preInit = 1; };
		class strongpointUtilPreInit { preInit = 1; };
		class taskPreInit { preInit = 1; };
		class tracePreInit { preInit = 1; };
		class vehicleCaptureParametersPreInit { preInit = 1; };
	};
};
